In [1]:
import requests

APP_ID = "c38ca6d6"
APP_KEY = "ffc26b7656248115eff37ba0ed9ef7e7"

url = "https://api.adzuna.com/v1/api/jobs/in/search/1"

params = {
    "app_id": APP_ID,
    "app_key": APP_KEY,
    "what": "data analyst",
    "where": "jaipur",
    "results_per_page": 20
}

response = requests.get(url, params=params)

print("Status Code:", response.status_code)

if response.status_code == 200:
    data = response.json()
    print("Total jobs found:", data["count"])
    print("\nFirst job title:", data["results"][0]["title"])
    print("Company:", data["results"][0]["company"]["display_name"])
else:
    print("Error:", response.text)

Status Code: 200
Total jobs found: 16

First job title: Data Analyst
Company: Mr n Mrs Pet

In [1]:
from collections import Counter
...
skill_counts = Counter(all_skills)
skills_df = pd.DataFrame(skill_counts.items(), columns=["Skill", "Count"]).sort_values("Count", ascending=False)
print(skills_df)

NameError: name 'all_skills' is not defined

In [4]:
jobs_list = []

for job in data["results"]:
    # .get() use karo company/location ke liye bhi, taaki missing fields pe crash na ho
    company_name = job.get("company", {}).get("display_name", "Not Available")
    location_name = job.get("location", {}).get("display_name", "Not Available")
    
    jobs_list.append({
        "title": job.get("title", "Not Available"),
        "company": company_name,
        "location": location_name,
        "salary_min": job.get("salary_min"),
        "salary_max": job.get("salary_max"),
        "created": job.get("created"),
        "description": job.get("description", "")
    })

df = pd.DataFrame(jobs_list)
df.head()

,title,company,location,salary_min,salary_max,created,description
0,Data Analyst,Mr n Mrs Pet,"Jaipur, Rajasthan",100000.0,300000.0,2022-07-22T06:48:32Z,Requirements: Bachelor’s degree from universit...
1,Senior Data Analyst,r3 Consultant,"Jaipur, Rajasthan",15.0,25.0,2026-01-11T06:39:06Z,Job Description: Senior Data Analyst Position ...
2,Senior Data Analyst - Business Insights,YourHRfolks,"Jaipur, Rajasthan",650000.0,1600000.0,2021-05-26T12:51:52Z,About Us Punchh is the leader in customer loya...
3,Data Engineer,Nexmec Automation,"Jaipur, Rajasthan",NaN,NaN,2026-06-05T14:54:57Z,Job Description We are looking for a skilled a...
4,PHP Developer,Charu Papers,"Jaipur, Rajasthan",500000.0,800000.0,2021-12-26T04:19:48Z,"Good knowledge of SQL and related databases, w..."

In [5]:
job_titles = ["data analyst", "business analyst", "data analytics", "reporting analyst", "mis executive"]

all_jobs = []

for title_keyword in job_titles:
    params = {
        "app_id": APP_ID,
        "app_key": APP_KEY,
        "what": title_keyword,
        "where": "jaipur",
        "results_per_page": 50
    }
    
    response = requests.get(url, params=params)
    
    if response.status_code == 200:
        data = response.json()
        print(f"'{title_keyword}' -> {data['count']} jobs found")
        
        for job in data["results"]:
            company_name = job.get("company", {}).get("display_name", "Not Available")
            location_name = job.get("location", {}).get("display_name", "Not Available")
            
            all_jobs.append({
                "search_keyword": title_keyword,
                "title": job.get("title", "Not Available"),
                "company": company_name,
                "location": location_name,
                "salary_min": job.get("salary_min"),
                "salary_max": job.get("salary_max"),
                "created": job.get("created"),
                "description": job.get("description", "")
            })
    else:
        print(f"Error for '{title_keyword}':", response.status_code)

print(f"\nTotal jobs collected: {len(all_jobs)}")

'data analyst' -> 16 jobs found
'business analyst' -> 32 jobs found
'data analytics' -> 73 jobs found
'reporting analyst' -> 1 jobs found
'mis executive' -> 2 jobs found

Total jobs collected: 101

In [6]:
# all_jobs list ko DataFrame (table) mein convert karo
df = pd.DataFrame(all_jobs)

# Duplicate jobs remove karo (kyunki same job 2 keywords mein aa sakti hai)
df = df.drop_duplicates(subset=["title", "company", "created"])

print(f"Total unique jobs: {len(df)}")
df.head(10)

Total unique jobs: 85

,search_keyword,title,company,location,salary_min,salary_max,created,description
0,data analyst,Data Analyst,Mr n Mrs Pet,"Jaipur, Rajasthan",100000.0,300000.0,2022-07-22T06:48:32Z,Requirements: Bachelor’s degree from universit...
1,data analyst,Senior Data Analyst,r3 Consultant,"Jaipur, Rajasthan",15.0,25.0,2026-01-11T06:39:06Z,Job Description: Senior Data Analyst Position ...
2,data analyst,Senior Data Analyst - Business Insights,YourHRfolks,"Jaipur, Rajasthan",650000.0,1600000.0,2021-05-26T12:51:52Z,About Us Punchh is the leader in customer loya...
3,data analyst,Data Engineer,Nexmec Automation,"Jaipur, Rajasthan",NaN,NaN,2026-06-05T14:54:57Z,Job Description We are looking for a skilled a...
4,data analyst,PHP Developer,Charu Papers,"Jaipur, Rajasthan",500000.0,800000.0,2021-12-26T04:19:48Z,"Good knowledge of SQL and related databases, w..."
5,data analyst,Power BI Developer,Resources Valley,"Jaipur, Rajasthan",600000.0,1600000.0,2025-08-27T05:48:43Z,"Key Responsibilities: Design, develop, and mai..."
6,data analyst,TeleSales Executive,Not Available,"Jaipur, Rajasthan",NaN,NaN,2024-05-10T07:38:31Z,"1 years of Telesales Experience in Bank, Insur..."
7,data analyst,Fullstack Developer,Memorres Digital Pvt Ltd,"Jaipur, Rajasthan",500000.0,800000.0,2021-11-14T04:22:10Z,Job brief We are looking for a Full Stack Deve...
8,data analyst,Nodejs API Developer,Celebal Technologies Pvt Ltd,"Jaipur, Rajasthan",300000.0,1800000.0,2023-06-20T17:01:50Z,Job Brief: We are looking for experience in AP...
9,data analyst,.NET Nodejs Developer,Celebal Technologies,"Jaipur, Rajasthan",300000.0,1500000.0,2022-08-26T06:41:21Z,Job Brief: We are looking for a C# .Net Develo...

In [7]:
job_titles = [
    "data analyst", "business analyst", "data analytics", 
    "reporting analyst", "mis executive",
    "fresher data analyst", "junior data analyst", "entry level data analyst"
]

In [8]:
# Duplicate jobs remove karo
df = pd.DataFrame(all_jobs)
df = df.drop_duplicates(subset=["title", "company", "created"])

print(f"Total unique jobs: {len(df)}")

# CSV mein save karo
df.to_csv("jaipur_data_analyst_jobs.csv", index=False)
print("Saved successfully as 'jaipur_data_analyst_jobs.csv'")

Total unique jobs: 85
Saved successfully as 'jaipur_data_analyst_jobs.csv'

In [9]:
# Salary columns ko numeric type mein convert karo (agar already nahi hai)
df["salary_min"] = pd.to_numeric(df["salary_min"], errors="coerce")
df["salary_max"] = pd.to_numeric(df["salary_max"], errors="coerce")

# Unrealistic salaries hata do (jaise jo 10,000 se kam hain - woh galat data hai, per-hour rate ho sakta hai)
df_clean = df[(df["salary_min"].isna()) | (df["salary_min"] >= 10000)]

print(f"Pehle rows: {len(df)}")
print(f"Cleaning ke baad rows: {len(df_clean)}")

df_clean.head()

Pehle rows: 85
Cleaning ke baad rows: 79

,search_keyword,title,company,location,salary_min,salary_max,created,description
0,data analyst,Data Analyst,Mr n Mrs Pet,"Jaipur, Rajasthan",100000.0,300000.0,2022-07-22T06:48:32Z,Requirements: Bachelor’s degree from universit...
2,data analyst,Senior Data Analyst - Business Insights,YourHRfolks,"Jaipur, Rajasthan",650000.0,1600000.0,2021-05-26T12:51:52Z,About Us Punchh is the leader in customer loya...
3,data analyst,Data Engineer,Nexmec Automation,"Jaipur, Rajasthan",NaN,NaN,2026-06-05T14:54:57Z,Job Description We are looking for a skilled a...
4,data analyst,PHP Developer,Charu Papers,"Jaipur, Rajasthan",500000.0,800000.0,2021-12-26T04:19:48Z,"Good knowledge of SQL and related databases, w..."
5,data analyst,Power BI Developer,Resources Valley,"Jaipur, Rajasthan",600000.0,1600000.0,2025-08-27T05:48:43Z,"Key Responsibilities: Design, develop, and mai..."

In [10]:
def categorize_experience(description):
    description = str(description).lower()
    if "fresher" in description or "0-1 year" in description or "entry level" in description or "no experience" in description:
        return "Fresher"
    elif "senior" in description or "5+ year" in description or "lead" in description:
        return "Senior"
    else:
        return "Mid-level / Not Specified"

df_clean["experience_level"] = df_clean["description"].apply(categorize_experience)

# Kitne fresher vs experienced jobs hain, dekho
df_clean["experience_level"].value_counts()

experience_level
Mid-level / Not Specified    59
Senior                       20
Name: count, dtype: int64

In [11]:
skills_list = ["sql", "excel", "python", "tableau", "power bi", "r programming", "machine learning", "statistics"]

def extract_skills(description):
    description = str(description).lower()
    found_skills = [skill for skill in skills_list if skill in description]
    return ", ".join(found_skills) if found_skills else "Not mentioned"

df_clean["skills_found"] = df_clean["description"].apply(extract_skills)

df_clean[["title", "company", "skills_found"]].head(10)

,title,company,skills_found
0,Data Analyst,Mr n Mrs Pet,Not mentioned
2,Senior Data Analyst - Business Insights,YourHRfolks,Not mentioned
3,Data Engineer,Nexmec Automation,Not mentioned
4,PHP Developer,Charu Papers,"sql, excel"
5,Power BI Developer,Resources Valley,power bi
6,TeleSales Executive,Not Available,Not mentioned
7,Fullstack Developer,Memorres Digital Pvt Ltd,Not mentioned
8,Nodejs API Developer,Celebal Technologies Pvt Ltd,Not mentioned
9,.NET Nodejs Developer,Celebal Technologies,Not mentioned
10,Full Stack Developer,Infomagine Softwares Pvt Ltd,Not mentioned

In [12]:
df_clean.to_csv("jaipur_jobs_cleaned.csv", index=False)
print("Cleaned data saved successfully!")
print(f"Total rows: {len(df_clean)}")
print(f"Columns: {list(df_clean.columns)}")

Cleaned data saved successfully!
Total rows: 79
Columns: ['search_keyword', 'title', 'company', 'location', 'salary_min', 'salary_max', 'created', 'description', 'experience_level', 'skills_found']

In [13]:
import pyodbc
print(pyodbc.drivers())

['SQL Server', 'SQL Server Native Client 10.0', 'SQL Server Native Client RDA 11.0', 'ODBC Driver 17 for SQL Server']

In [15]:
from sqlalchemy import create_engine
import urllib

server = 'localhost'
database = 'DataAnalystProject'

params = urllib.parse.quote_plus(
    f"DRIVER={{ODBC Driver 17 for SQL Server}};"
    f"SERVER={server};"
    f"DATABASE={database};"
    f"Trusted_Connection=yes;"
)

engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

try:
    connection = engine.connect()
    print("Connection successful!")
    connection.close()
except Exception as e:
    print("Connection failed:", e)

Connection successful!

In [16]:
# df_clean ko SQL Server table mein daal do
df_clean.to_sql("jaipur_jobs", engine, if_exists="replace", index=False)

print("Data successfully loaded into SQL Server!")
print(f"Total rows loaded: {len(df_clean)}")

Data successfully loaded into SQL Server!
Total rows loaded: 79

In [18]:
df_clean.to_excel("jaipur_jobs_for_excel.xlsx", index=False, sheet_name="Raw Data")
print("Excel file created!")

Excel file created!

In [19]:
from collections import Counter

# Saare skills ko ek list mein todo (comma se split karke)
all_skills = []
for skills_str in df_clean["skills_found"]:
    if skills_str != "Not mentioned":
        skills = [s.strip() for s in skills_str.split(",")]
        all_skills.extend(skills)

# Count karo har skill kitni baar aayi
skill_counts = Counter(all_skills)

# DataFrame banao taaki Excel mein export kar sakein
skills_df = pd.DataFrame(skill_counts.items(), columns=["Skill", "Count"]).sort_values("Count", ascending=False)

print(skills_df)

              Skill  Count
1             excel     10
0               sql      4
2          power bi      3
3            python      2
4  machine learning      1

In [21]:
# Existing Excel file mein nayi sheet add karo skills data ke saath
with pd.ExcelWriter("jaipur_jobs_for_excel.xlsx", engine="openpyxl", mode="a", if_sheet_exists="replace") as writer:
    skills_df.to_excel(writer, sheet_name="Skills Summary", index=False)

print("Skills data added to Excel!")

Skills data added to Excel!